cmake_minimum_required(VERSION 3.31)
project(cxcore)

include(CTest)

if(CX_BUILD_STATIC)
    add_library(cxcore STATIC)
    target_compile_definitions(cxcore PUBLIC CX_STATIC_LINK)
else()
    add_library(cxcore SHARED)
endif()
target_compile_definitions(cxcore PRIVATE CX_CXCORE_BUILD)
add_subdirectory(inc)
add_subdirectory(platform)
add_subdirectory(src)
if(BUILD_TESTING)
    add_subdirectory(tests)
endif()
