// This is an autogenerated C source file for project 'cxcore'

#include "cxcore.h"

//
// Strings
//

CX_STRING_DEF(CX_ID_3(__name, System, Object), "Object");
CX_STRING_DEF(CX_ID_3(__name, System, Nullable), "Nullable");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, TypeInfo), "TypeInfo");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, VersionInfo), "VersionInfo");
CX_STRING_DEF(CX_ID_3(__name, System, Array), "Array");
CX_STRING_DEF(CX_ID_3(__name, System, Attribute), "Attribute");
CX_STRING_DEF(CX_ID_3(__name, System, Bool), "Bool");
CX_STRING_DEF(CX_ID_3(__name, System, Byte), "Byte");
CX_STRING_DEF(CX_ID_3(__name, System, Char), "Char");
CX_STRING_DEF(CX_ID_3(__name, System, Console), "Console");
CX_STRING_DEF(CX_ID_3(__name, System, DateTime), "DateTime");
CX_STRING_DEF(CX_ID_3(__name, System, Double), "Double");
CX_STRING_DEF(CX_ID_3(__name, System, Environment), "Environment");
CX_STRING_DEF(CX_ID_3(__name, System, Exception), "Exception");
CX_STRING_DEF(CX_ID_3(__name, System, Float), "Float");
CX_STRING_DEF(CX_ID_3(__name, System, IDateTimeProvider), "IDateTimeProvider");
CX_STRING_DEF(CX_ID_3(__name, System, IReader), "IReader");
CX_STRING_DEF(CX_ID_3(__name, System, IWriter), "IWriter");
CX_STRING_DEF(CX_ID_3(__name, System, Int), "Int");
CX_STRING_DEF(CX_ID_3(__name, System, Long), "Long");
CX_STRING_DEF(CX_ID_3(__name, System, Math), "Math");
CX_STRING_DEF(CX_ID_3(__name, System, Memory), "Memory");
CX_STRING_DEF(CX_ID_3(__name, System, Random), "Random");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, FieldInfo), "FieldInfo");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, FunctionInfo), "FunctionInfo");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, FunctionParamInfo), "FunctionParamInfo");
CX_STRING_DEF(CX_ID_4(__name, System, Reflection, ModuleInfo), "ModuleInfo");
CX_STRING_DEF(CX_ID_3(__name, System, SByte), "SByte");
CX_STRING_DEF(CX_ID_3(__name, System, Short), "Short");
CX_STRING_DEF(CX_ID_3(__name, System, String), "String");
CX_STRING_DEF(CX_ID_3(__name, System, SystemDateTimeProvider), "SystemDateTimeProvider");
CX_STRING_DEF(CX_ID_3(__name, System, TimeSpan), "TimeSpan");
CX_STRING_DEF(CX_ID_3(__name, System, UInt), "UInt");
CX_STRING_DEF(CX_ID_3(__name, System, ULong), "ULong");
CX_STRING_DEF(CX_ID_3(__name, System, UShort), "UShort");
CX_STRING_DEF(CX_ID_3(__name, System, Uuid), "Uuid");
CX_STRING_DEF(CX_ID_3(__name, System, Void), "Void");
CX_STRING_DEF(CX_ID_2(__namespace, System), "System");
CX_STRING_DEF(CX_ID_3(__namespace, System, Reflection), "System.Reflection");
CX_STRING_DEF(CX_ID_2(cxcore, __string_076DE6E730DF0B4C), "false");
CX_STRING_DEF(CX_ID_2(cxcore, __string_18D10C7D2B4B04AA), "true");

//
// Static fields
//

const struct CX_ID_3(cxcore, System, String)* CX_ID_4(cxcore, System, Bool, FalseString) = &CX_ID_2(cxcore, __string_076DE6E730DF0B4C);
const struct CX_ID_3(cxcore, System, String)* CX_ID_4(cxcore, System, Bool, TrueString) = &CX_ID_2(cxcore, __string_18D10C7D2B4B04AA);
cx_byte CX_ID_4(cxcore, System, Byte, MinValue);
cx_byte CX_ID_4(cxcore, System, Byte, MaxValue);
cx_double CX_ID_4(cxcore, System, Double, MinValue);
cx_double CX_ID_4(cxcore, System, Double, MaxValue);
cx_float CX_ID_4(cxcore, System, Float, MinValue);
cx_float CX_ID_4(cxcore, System, Float, MaxValue);
cx_int CX_ID_4(cxcore, System, Int, MinValue);
cx_int CX_ID_4(cxcore, System, Int, MaxValue);
cx_long CX_ID_4(cxcore, System, Long, MinValue);
cx_long CX_ID_4(cxcore, System, Long, MaxValue);
cx_double CX_ID_4(cxcore, System, Math, E);
cx_double CX_ID_4(cxcore, System, Math, Pi);
cx_double CX_ID_4(cxcore, System, Math, Tau);
cx_double CX_ID_4(cxcore, System, Math, Sqrt2);
cx_double CX_ID_4(cxcore, System, Math, Sqrt3);
cx_sbyte CX_ID_4(cxcore, System, SByte, MinValue);
cx_sbyte CX_ID_4(cxcore, System, SByte, MaxValue);
cx_short CX_ID_4(cxcore, System, Short, MinValue);
cx_short CX_ID_4(cxcore, System, Short, MaxValue);
cx_uint CX_ID_4(cxcore, System, UInt, MinValue);
cx_uint CX_ID_4(cxcore, System, UInt, MaxValue);
cx_ulong CX_ID_4(cxcore, System, ULong, MinValue);
cx_ulong CX_ID_4(cxcore, System, ULong, MaxValue);
cx_ushort CX_ID_4(cxcore, System, UShort, MinValue);
cx_ushort CX_ID_4(cxcore, System, UShort, MaxValue);
struct CX_ID_3(cxcore, System, Uuid) CX_ID_4(cxcore, System, Uuid, Zero);
struct CX_ID_3(cxcore, System, Void) CX_ID_4(cxcore, System, Void, Unit);

//
// Interface dispatch thunks
//

extern union cx_vtable_entry CX_ID_7(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable)[];

static struct CX_ID_3(cxcore, System, DateTime) CX_ID_8(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable, slot_1)(cx_ptr __root) {
    return CX_ID_4(cxcore, System, SystemDateTimeProvider, GetUtcNow)((const struct CX_ID_3(cxcore, System, SystemDateTimeProvider)*)__root);
}

static struct CX_ID_3(cxcore, System, DateTime) CX_ID_8(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable, slot_2)(cx_ptr __root) {
    return CX_ID_4(cxcore, System, SystemDateTimeProvider, GetLocalNow)((const struct CX_ID_3(cxcore, System, SystemDateTimeProvider)*)__root);
}


//
// TypeInfos
//

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Object))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Object), CX_ID_3(__name, System, Object), CX_ID_2(__namespace, System), 0x5B2C299D96534DC7, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Nullable))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Nullable), CX_ID_3(__name, System, Nullable), CX_ID_2(__namespace, System), 0x8056F9FF7F517DAA, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, TypeInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, TypeInfo), CX_ID_4(__name, System, Reflection, TypeInfo), CX_ID_3(__namespace, System, Reflection), 0x9C779CB20AC317E6, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, VersionInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, VersionInfo), CX_ID_4(__name, System, Reflection, VersionInfo), CX_ID_3(__namespace, System, Reflection), 0x2F88BC4F12FAF108, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Array))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Array), CX_ID_3(__name, System, Array), CX_ID_2(__namespace, System), CX_ID_4(cxcore, System, Object, __typeinfo), 0x3C9E25CCCADC6003, CX_REFLECTION_FLAG_FINAL | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Attribute))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Attribute), CX_ID_3(__name, System, Attribute), CX_ID_2(__namespace, System), CX_ID_4(cxcore, System, Object, __typeinfo), 0x166B532331C23EB3, CX_REFLECTION_FLAG_ABSTRACT | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Bool))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Bool), CX_ID_3(__name, System, Bool), CX_ID_2(__namespace, System), 0xA34F98ECCCEBDD8A, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Byte))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Byte), CX_ID_3(__name, System, Byte), CX_ID_2(__namespace, System), 0x177BDF84A821EF27, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Char))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Char), CX_ID_3(__name, System, Char), CX_ID_2(__namespace, System), 0xF5AE9C37D1B267, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_STATIC_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Console), CX_ID_3(__name, System, Console), CX_ID_2(__namespace, System), 0xDBEE0C466C77BB2A, CX_REFLECTION_FLAG_STATIC | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, DateTime))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, DateTime), CX_ID_3(__name, System, DateTime), CX_ID_2(__namespace, System), 0x4C58FBA7AF5E50FA, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Double))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Double), CX_ID_3(__name, System, Double), CX_ID_2(__namespace, System), 0xA64643F3071D1390, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_STATIC_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Environment), CX_ID_3(__name, System, Environment), CX_ID_2(__namespace, System), 0x4461ED56370B34C8, CX_REFLECTION_FLAG_STATIC | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Exception))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Exception), CX_ID_3(__name, System, Exception), CX_ID_2(__namespace, System), CX_ID_4(cxcore, System, Object, __typeinfo), 0x167E0BF22010EA5B, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Float))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Float), CX_ID_3(__name, System, Float), CX_ID_2(__namespace, System), 0xE3544ABBD54A5C50, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, IDateTimeProvider))
{ .function = (cx_vtable_function)0 },
{ .function = (cx_vtable_function)0 },
CX_END_VTABLE_DEF;
CX_INTERFACE_TYPEINFO_DEF(CX_ID_3(cxcore, System, IDateTimeProvider), CX_ID_3(__name, System, IDateTimeProvider), CX_ID_2(__namespace, System), 0x629F60CC6CF45084, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_INTERFACE);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, IReader))
{ .function = (cx_vtable_function)0 },
CX_END_VTABLE_DEF;
CX_INTERFACE_TYPEINFO_DEF(CX_ID_3(cxcore, System, IReader), CX_ID_3(__name, System, IReader), CX_ID_2(__namespace, System), 0x2759E6C2F9286CDB, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_INTERFACE);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, IWriter))
{ .function = (cx_vtable_function)0 },
CX_END_VTABLE_DEF;
CX_INTERFACE_TYPEINFO_DEF(CX_ID_3(cxcore, System, IWriter), CX_ID_3(__name, System, IWriter), CX_ID_2(__namespace, System), 0x48DAE5D4E97F1C21, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_INTERFACE);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Int))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Int), CX_ID_3(__name, System, Int), CX_ID_2(__namespace, System), 0xF8879D072BAFAC5A, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Long))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Long), CX_ID_3(__name, System, Long), CX_ID_2(__namespace, System), 0xDAD149DA09DC5DD9, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_STATIC_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Math), CX_ID_3(__name, System, Math), CX_ID_2(__namespace, System), 0xFE57073966243915, CX_REFLECTION_FLAG_STATIC | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_STATIC_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, Memory), CX_ID_3(__name, System, Memory), CX_ID_2(__namespace, System), 0xA265F5767F8BE420, CX_REFLECTION_FLAG_STATIC | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Random))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Random), CX_ID_3(__name, System, Random), CX_ID_2(__namespace, System), 0xC511DB78EEE8A4F6, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, FieldInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, FieldInfo), CX_ID_4(__name, System, Reflection, FieldInfo), CX_ID_3(__namespace, System, Reflection), 0x31E96AD242234FB9, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, FunctionInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, FunctionInfo), CX_ID_4(__name, System, Reflection, FunctionInfo), CX_ID_3(__namespace, System, Reflection), 0x9580515B485D0C4F, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, FunctionParamInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, FunctionParamInfo), CX_ID_4(__name, System, Reflection, FunctionParamInfo), CX_ID_3(__namespace, System, Reflection), 0xC29ED0395BA7A271, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_4(cxcore, System, Reflection, ModuleInfo))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_4(cxcore, System, Reflection, ModuleInfo), CX_ID_4(__name, System, Reflection, ModuleInfo), CX_ID_3(__namespace, System, Reflection), 0xC4CE46ADD6DCACCA, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, SByte))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, SByte), CX_ID_3(__name, System, SByte), CX_ID_2(__namespace, System), 0xC58951797E89C922, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Short))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Short), CX_ID_3(__name, System, Short), CX_ID_2(__namespace, System), 0xCA15721E09C0E056, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, String))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, String), CX_ID_3(__name, System, String), CX_ID_2(__namespace, System), CX_ID_4(cxcore, System, Object, __typeinfo), 0x39E2CB3A11136EA4, CX_REFLECTION_FLAG_FINAL | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, SystemDateTimeProvider))
CX_END_VTABLE_DEF;
CX_CLASS_TYPEINFO_DEF(CX_ID_3(cxcore, System, SystemDateTimeProvider), CX_ID_3(__name, System, SystemDateTimeProvider), CX_ID_2(__namespace, System), CX_ID_4(cxcore, System, Object, __typeinfo), 0xCCBF40D50C28DF82, CX_REFLECTION_FLAG_FINAL | CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_CLASS);
CX_BEGIN_INTERFACE_VTABLE_DEF(CX_ID_7(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable), CX_ID_3(cxcore, System, IDateTimeProvider))
CX_VTABLE_ENTRY(CX_ID_8(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable, slot_1))
CX_VTABLE_ENTRY(CX_ID_8(cxcore, System, SystemDateTimeProvider, __iface, System, IDateTimeProvider, __vtable, slot_2))
CX_END_VTABLE_DEF;

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, TimeSpan))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, TimeSpan), CX_ID_3(__name, System, TimeSpan), CX_ID_2(__namespace, System), 0x10401DE7EE8E5B67, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, UInt))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, UInt), CX_ID_3(__name, System, UInt), CX_ID_2(__namespace, System), 0xAF26E4A450FAB71D, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, ULong))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, ULong), CX_ID_3(__name, System, ULong), CX_ID_2(__namespace, System), 0xF00D8ADC25BFB778, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, UShort))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, UShort), CX_ID_3(__name, System, UShort), CX_ID_2(__namespace, System), 0x47490139B33626B2, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Uuid))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Uuid), CX_ID_3(__name, System, Uuid), CX_ID_2(__namespace, System), 0xB88D688F740EC52C, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

CX_BEGIN_VTABLE_DEF(CX_ID_3(cxcore, System, Void))
CX_END_VTABLE_DEF;
CX_STRUCT_TYPEINFO_DEF(CX_ID_3(cxcore, System, Void), CX_ID_3(__name, System, Void), CX_ID_2(__namespace, System), 0x4A3D776A6B34A455, CX_REFLECTION_FLAG_VISIBILITY_PUBLIC | CX_REFLECTION_FLAG_TYPE_STRUCT);

//
// Functions
//

cx_bool CX_ID_5(cxcore, System, Char, IsDigit, __const_get)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return CX_ID_4(cxcore, System, Char, IsBetween)(__this->_value, '0', '9');
}

cx_bool CX_ID_5(cxcore, System, Char, IsLower, __const_get)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return CX_ID_4(cxcore, System, Char, IsBetween)(__this->_value, 'a', 'z');
}

cx_bool CX_ID_5(cxcore, System, Char, IsUpper, __const_get)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return CX_ID_4(cxcore, System, Char, IsBetween)(__this->_value, 'A', 'Z');
}

cx_bool CX_ID_5(cxcore, System, Char, IsLetter, __const_get)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return (CX_ID_5(cxcore, System, Char, IsLower, __const_get)(__this) || CX_ID_5(cxcore, System, Char, IsUpper, __const_get)(__this));
}

cx_bool CX_ID_5(cxcore, System, Char, IsWhiteSpace, __const_get)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return ((((__this->_value == ' ') || (__this->_value == '\t')) || (__this->_value == '\r')) || (__this->_value == '\n'));
}

cx_bool CX_ID_4(cxcore, System, Char, IsBetween)(cx_char c, cx_char min, cx_char max) {
    return ((c >= min) && (c <= max));
}

cx_char CX_ID_4(cxcore, System, Char, ToLower)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return (CX_ID_5(cxcore, System, Char, IsUpper, __const_get)(&(__this)) ? ((__this->_value + 'a') - 'A') : __this->_value);
}

cx_char CX_ID_4(cxcore, System, Char, ToUpper)(const struct CX_ID_3(cxcore, System, Char)* __this) {
    return (CX_ID_5(cxcore, System, Char, IsLower, __const_get)(&(__this)) ? ((__this->_value + 'A') - 'a') : __this->_value);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, Hours, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    return (CX_ID_5(cxcore, System, TimeSpan, TotalHours, __const_get)(__this) % 24l);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, Minutes, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    return (CX_ID_5(cxcore, System, TimeSpan, TotalMinutes, __const_get)(__this) % 60l);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, Seconds, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    return (CX_ID_5(cxcore, System, TimeSpan, TotalSeconds, __const_get)(__this) % 60l);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, Milliseconds, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    return __this->_milliseconds;
}

cx_long CX_ID_5(cxcore, System, TimeSpan, TotalDays, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    cx_long divider = (((24l * 60l) * 60l) * 1000l);
    return (__this->_milliseconds / divider);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, TotalHours, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    cx_long divider = ((60l * 60l) * 1000l);
    return (__this->_milliseconds / divider);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, TotalMinutes, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    cx_long divider = (60l * 1000l);
    return (__this->_milliseconds / divider);
}

cx_long CX_ID_5(cxcore, System, TimeSpan, TotalSeconds, __const_get)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this) {
    cx_long divider = 1000l;
    return (__this->_milliseconds / divider);
}

void CX_ID_4(cxcore, System, TimeSpan, __constructor)(struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long milliseconds) {
    __this->_milliseconds = milliseconds;
}

void CX_ID_5(cxcore, System, TimeSpan, __constructor, _2)(struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long days, cx_long hours, cx_long minutes, cx_long seconds, cx_long milliseconds) {
    __this->_milliseconds = ((((((((days * 24l) * 60l) * 60l) * 1000l) + (((hours * 60l) * 60l) * 1000l)) + ((minutes * 60l) * 1000l)) + (seconds * 1000l)) + milliseconds);
}

struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddDays)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long days) {
    cx_long multiplier = (((24l * 60l) * 60l) * 1000l);
    struct CX_ID_3(cxcore, System, TimeSpan) __cx_new_0;
    return (CX_ID_4(cxcore, System, TimeSpan, __constructor)(&__cx_new_0, (__this->_milliseconds + (days * multiplier))), __cx_new_0);
}

struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddHours)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long hours) {
    cx_long multiplier = ((60l * 60l) * 1000l);
    struct CX_ID_3(cxcore, System, TimeSpan) __cx_new_0;
    return (CX_ID_4(cxcore, System, TimeSpan, __constructor)(&__cx_new_0, (__this->_milliseconds + (hours * multiplier))), __cx_new_0);
}

struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddMinutes)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long minutes) {
    cx_long multiplier = (60l * 1000l);
    struct CX_ID_3(cxcore, System, TimeSpan) __cx_new_0;
    return (CX_ID_4(cxcore, System, TimeSpan, __constructor)(&__cx_new_0, (__this->_milliseconds + (minutes * multiplier))), __cx_new_0);
}

struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddSeconds)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long seconds) {
    cx_long multiplier = 1000l;
    struct CX_ID_3(cxcore, System, TimeSpan) __cx_new_0;
    return (CX_ID_4(cxcore, System, TimeSpan, __constructor)(&__cx_new_0, (__this->_milliseconds + (seconds * multiplier))), __cx_new_0);
}

struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddMilliseconds)(const struct CX_ID_3(cxcore, System, TimeSpan)* __this, cx_long milliseconds) {
    struct CX_ID_3(cxcore, System, TimeSpan) __cx_new_0;
    return (CX_ID_4(cxcore, System, TimeSpan, __constructor)(&__cx_new_0, (__this->_milliseconds + milliseconds)), __cx_new_0);
}

