// This is an autogenerated C header file for project 'cxcore'

#ifndef _CXCORE_H_
#define _CXCORE_H_

#include <cx.h>

//
// Forward type declarations
//

struct CX_ID_3(cxcore, System, Object);
struct CX_ID_3(cxcore, System, Nullable);
struct CX_ID_4(cxcore, System, Reflection, TypeInfo);
struct CX_ID_4(cxcore, System, Reflection, VersionInfo);
struct CX_ID_3(cxcore, System, Array);
struct CX_ID_3(cxcore, System, Attribute);
struct CX_ID_3(cxcore, System, Bool);
struct CX_ID_3(cxcore, System, Byte);
struct CX_ID_3(cxcore, System, Char);
struct CX_ID_3(cxcore, System, Console);
struct CX_ID_3(cxcore, System, DateTime);
struct CX_ID_3(cxcore, System, Double);
struct CX_ID_3(cxcore, System, Environment);
struct CX_ID_3(cxcore, System, Exception);
struct CX_ID_3(cxcore, System, Float);
struct CX_ID_3(cxcore, System, IDateTimeProvider);
struct CX_ID_3(cxcore, System, IReader);
struct CX_ID_3(cxcore, System, IWriter);
struct CX_ID_3(cxcore, System, Int);
struct CX_ID_3(cxcore, System, Long);
struct CX_ID_3(cxcore, System, Math);
struct CX_ID_3(cxcore, System, Memory);
struct CX_ID_3(cxcore, System, Random);
struct CX_ID_4(cxcore, System, Reflection, FieldInfo);
struct CX_ID_4(cxcore, System, Reflection, FunctionInfo);
struct CX_ID_4(cxcore, System, Reflection, FunctionParamInfo);
struct CX_ID_4(cxcore, System, Reflection, ModuleInfo);
struct CX_ID_3(cxcore, System, SByte);
struct CX_ID_3(cxcore, System, Short);
struct CX_ID_3(cxcore, System, String);
struct CX_ID_3(cxcore, System, SystemDateTimeProvider);
struct CX_ID_3(cxcore, System, TimeSpan);
struct CX_ID_3(cxcore, System, UInt);
struct CX_ID_3(cxcore, System, ULong);
struct CX_ID_3(cxcore, System, UShort);
struct CX_ID_3(cxcore, System, Uuid);
struct CX_ID_3(cxcore, System, Void);

//
// Type declarations
//

CX_TYPE_DEF(CX_ID_3(cxcore, System, Object)) {
    void* __vtable;
    cx_ptr _gc;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Nullable)) {
    cx_ptr _obj;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, TypeInfo)) {
    cx_ulong Hash;
    cx_uint Flags;
    cx_uint Size;
    struct CX_ID_3(cxcore, System, String)* Name;
    struct CX_ID_3(cxcore, System, String)* Namespace;
    struct CX_ID_3(cxcore, System, Array)* GenericParams;
    struct CX_ID_3(cxcore, System, Nullable) BaseType;
    struct CX_ID_3(cxcore, System, Array)* Interfaces;
    struct CX_ID_3(cxcore, System, Array)* Fields;
    struct CX_ID_3(cxcore, System, Array)* Functions;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, VersionInfo)) {
    cx_int Major;
    cx_int Minor;
    cx_int Patch;
    cx_int Revision;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Array)) {
    struct CX_ID_3(cxcore, System, Object) __base;
    cx_uint _length;
    cx_ptr _data;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Attribute)) {
    struct CX_ID_3(cxcore, System, Object) __base;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Bool)) {
    cx_bool _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Byte)) {
    cx_byte _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Char)) {
    cx_char _value;
};
CX_STATIC_TYPE_DEF(CX_ID_3(cxcore, System, Console));
CX_TYPE_DEF(CX_ID_3(cxcore, System, DateTime)) {
    cx_ulong _ticks;
    cx_short _offset;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Double)) {
    cx_double _value;
};
CX_STATIC_TYPE_DEF(CX_ID_3(cxcore, System, Environment));
CX_TYPE_DEF(CX_ID_3(cxcore, System, Exception)) {
    struct CX_ID_3(cxcore, System, Object) __base;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Float)) {
    cx_float _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, IDateTimeProvider)) {
    void* __vtable;
    void* __root;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, IReader)) {
    void* __vtable;
    void* __root;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, IWriter)) {
    void* __vtable;
    void* __root;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Int)) {
    cx_int _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Long)) {
    cx_long _value;
};
CX_STATIC_TYPE_DEF(CX_ID_3(cxcore, System, Math));
CX_STATIC_TYPE_DEF(CX_ID_3(cxcore, System, Memory));
CX_TYPE_DEF(CX_ID_3(cxcore, System, Random)) {
    cx_uint _seed;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, FieldInfo)) {
    cx_uint Flags;
    cx_uint Offset;
    struct CX_ID_4(cxcore, System, Reflection, TypeInfo) Type;
    struct CX_ID_3(cxcore, System, String)* Name;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, FunctionInfo)) {
    cx_uint Flags;
    cx_uint Offset;
    struct CX_ID_4(cxcore, System, Reflection, TypeInfo) ReturnType;
    struct CX_ID_3(cxcore, System, String)* Name;
    struct CX_ID_3(cxcore, System, Array)* Params;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, FunctionParamInfo)) {
    cx_uint Flags;
    struct CX_ID_4(cxcore, System, Reflection, TypeInfo) Type;
    struct CX_ID_3(cxcore, System, String)* Name;
    cx_ptr DefaultValue;
};
CX_TYPE_DEF(CX_ID_4(cxcore, System, Reflection, ModuleInfo)) {
    cx_uint Flags;
    struct CX_ID_3(cxcore, System, String)* Name;
    struct CX_ID_4(cxcore, System, Reflection, VersionInfo) Version;
    struct CX_ID_3(cxcore, System, String)* Description;
    struct CX_ID_3(cxcore, System, String)* Author;
    struct CX_ID_3(cxcore, System, Array)* Types;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, SByte)) {
    cx_sbyte _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Short)) {
    cx_short _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, String)) {
    struct CX_ID_3(cxcore, System, Object) __base;
    cx_uint _length;
    cx_ptr _data;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, SystemDateTimeProvider)) {
    struct CX_ID_3(cxcore, System, Object) __base;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, TimeSpan)) {
    cx_ulong _ticks;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, UInt)) {
    cx_uint _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, ULong)) {
    cx_ulong _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, UShort)) {
    cx_ushort _value;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Uuid)) {
    cx_uint _a;
    cx_uint _b;
    cx_uint _c;
    cx_uint _d;
};
CX_TYPE_DEF(CX_ID_3(cxcore, System, Void)) {
    cx_byte __dummy;
};

//
// Function and property declarations
//

extern CX_EXPORT struct CX_ID_4(cxcore, System, Reflection, TypeInfo) CX_ID_5(cxcore, System, Object, Type, __const_get)(
    const struct CX_ID_3(cxcore, System, Object)* __this    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Object, __constructor)(
    struct CX_ID_3(cxcore, System, Object)* __this    
);
extern CX_EXPORT void CX_ID_5(cxcore, System, Nullable, Null, __const_get)(
    void* __returnValue);
extern CX_EXPORT cx_bool CX_ID_5(cxcore, System, Nullable, HasValue, __const_get)(
    const struct CX_ID_3(cxcore, System, Nullable)* __this    
);
extern CX_EXPORT void CX_ID_5(cxcore, System, Nullable, Value, __const_get)(
    const struct CX_ID_3(cxcore, System, Nullable)* __this,
    void* __returnValue    
);
extern CX_EXPORT  void CX_ID_5(cxcore, System, Nullable, Value, __set)(
    struct CX_ID_3(cxcore, System, Nullable)* __this,
    void* value    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Nullable, __constructor)(
    struct CX_ID_3(cxcore, System, Nullable)* __this,
    cx_ptr obj
);
extern CX_EXPORT void CX_ID_5(cxcore, System, Reflection, VersionInfo, __constructor)(
    struct CX_ID_4(cxcore, System, Reflection, VersionInfo)* __this,
    cx_int major,
    cx_int minor,
    cx_int patch,
    cx_int revision
);
extern CX_EXPORT const void CX_ID_5(cxcore, System, Array, Empty, __const_get)(
    void* __returnValue);
extern CX_EXPORT const cx_uint CX_ID_5(cxcore, System, Array, Length, __const_get)(
    struct CX_ID_3(cxcore, System, Array)* __this    
);
extern CX_EXPORT  void CX_ID_5(cxcore, System, Array, Item, __get)(
    struct CX_ID_3(cxcore, System, Array)* __this,
    void* __returnValue    
);
extern CX_EXPORT const void CX_ID_5(cxcore, System, Array, Item, __const_get)(
    struct CX_ID_3(cxcore, System, Array)* __this,
    void* __returnValue    
);
extern CX_EXPORT  void CX_ID_5(cxcore, System, Array, Item, __set)(
    struct CX_ID_3(cxcore, System, Array)* __this,
    void* __returnValue    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Array, __constructor)(
    struct CX_ID_3(cxcore, System, Array)* __this,
    cx_uint length
);
extern void CX_ID_4(cxcore, System, Attribute, __constructor)(
    struct CX_ID_3(cxcore, System, Attribute)* __this    
);
extern CX_EXPORT const cx_bool CX_ID_5(cxcore, System, Bool, False, __const_get)();
extern CX_EXPORT const cx_bool CX_ID_5(cxcore, System, Bool, True, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Bool, FalseString, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Bool, TrueString, __const_get)();
extern CX_EXPORT const cx_byte CX_ID_5(cxcore, System, Byte, MinValue, __const_get)();
extern CX_EXPORT const cx_byte CX_ID_5(cxcore, System, Byte, MaxValue, __const_get)();
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsBetween)(
    cx_char c,
    cx_char min,
    cx_char max
);
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsDigit)(
    cx_char c
);
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsLetter)(
    cx_char c
);
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsWhiteSpace)(
    cx_char c
);
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsLower)(
    cx_char c
);
extern CX_EXPORT cx_bool CX_ID_4(cxcore, System, Char, IsUpper)(
    cx_char c
);
extern CX_EXPORT cx_char CX_ID_4(cxcore, System, Char, ToLower)(
    const struct CX_ID_3(cxcore, System, Char)* __this    
);
extern CX_EXPORT cx_char CX_ID_4(cxcore, System, Char, ToUpper)(
    const struct CX_ID_3(cxcore, System, Char)* __this    
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Char, NumBytes)(
    const struct CX_ID_3(cxcore, System, Char)* __this    
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, String)* CX_ID_4(cxcore, System, Console, Read)(
    cx_uint length
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, String)* CX_ID_4(cxcore, System, Console, ReadLine)();
extern CX_EXPORT cx_uint CX_ID_4(cxcore, System, Console, Write)(
    const struct CX_ID_3(cxcore, System, String)* str
);
extern CX_EXPORT cx_uint CX_ID_4(cxcore, System, Console, WriteLine)(
    const struct CX_ID_3(cxcore, System, String)* str
);
extern CX_EXPORT const cx_ulong CX_ID_5(cxcore, System, DateTime, Ticks, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_short CX_ID_5(cxcore, System, DateTime, Offset, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Year, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Month, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Day, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, DayOfWeek, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Hour, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Minute, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Second, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, DateTime, Millisecond, __const_get)(
    struct CX_ID_3(cxcore, System, DateTime)* __this    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, DateTime, __constructor)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_ulong ticks,
    cx_short offset
);
extern CX_EXPORT void CX_ID_5(cxcore, System, DateTime, __constructor, _2)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int year,
    cx_int month,
    cx_int day,
    cx_int hour,
    cx_int minute,
    cx_int second,
    cx_int millisecond,
    cx_short offset
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddYears)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int years
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddMonths)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int months
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddDays)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int days
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddHours)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int hours
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddMinutes)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int minutes
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddSeconds)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int seconds
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, DateTime, AddMilliseconds)(
    struct CX_ID_3(cxcore, System, DateTime)* __this,
    cx_int milliseconds
);
extern CX_EXPORT const cx_double CX_ID_5(cxcore, System, Double, MinValue, __const_get)();
extern CX_EXPORT const cx_double CX_ID_5(cxcore, System, Double, MaxValue, __const_get)();
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, Double, Sign, __const_get)(
    struct CX_ID_3(cxcore, System, Double)* __this    
);
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Environment, SystemName, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Environment, NewLine, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Exception, Message, __const_get)(
    struct CX_ID_3(cxcore, System, Exception)* __this    
);
extern CX_EXPORT const struct CX_ID_3(cxcore, System, Nullable) CX_ID_5(cxcore, System, Exception, InnerException, __const_get)(
    struct CX_ID_3(cxcore, System, Exception)* __this    
);
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, Exception, StackTrace, __const_get)(
    struct CX_ID_3(cxcore, System, Exception)* __this    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Exception, __constructor)(
    struct CX_ID_3(cxcore, System, Exception)* __this    
);
extern CX_EXPORT void CX_ID_5(cxcore, System, Exception, __constructor, _2)(
    struct CX_ID_3(cxcore, System, Exception)* __this,
    struct CX_ID_3(cxcore, System, String)* message
);
extern CX_EXPORT void CX_ID_5(cxcore, System, Exception, __constructor, _3)(
    struct CX_ID_3(cxcore, System, Exception)* __this,
    struct CX_ID_3(cxcore, System, String)* message,
    struct CX_ID_3(cxcore, System, Exception)* innerException
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Exception, Throw)(
    struct CX_ID_3(cxcore, System, Exception)* exception
);
extern CX_EXPORT const cx_float CX_ID_5(cxcore, System, Float, MinValue, __const_get)();
extern CX_EXPORT const cx_float CX_ID_5(cxcore, System, Float, MaxValue, __const_get)();
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, Float, Sign, __const_get)(
    struct CX_ID_3(cxcore, System, Float)* __this    
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, IDateTimeProvider, GetUtcNow)(
    struct CX_ID_3(cxcore, System, IDateTimeProvider)* __this    
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, IDateTimeProvider, GetLocalNow)(
    struct CX_ID_3(cxcore, System, IDateTimeProvider)* __this    
);
extern CX_EXPORT cx_uint CX_ID_4(cxcore, System, IReader, Read)(
    struct CX_ID_3(cxcore, System, IReader)* __this,
    cx_uint length,
    cx_ptr buf
);
extern CX_EXPORT cx_uint CX_ID_4(cxcore, System, IWriter, Write)(
    struct CX_ID_3(cxcore, System, IWriter)* __this,
    cx_uint length,
    cx_ptr buf
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, Int, MinValue, __const_get)();
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, Int, MaxValue, __const_get)();
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, Long, MinValue, __const_get)();
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, Long, MaxValue, __const_get)();
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Abs)(
    cx_int value
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Abs, _2)(
    cx_long value
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Abs, _3)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Abs, _4)(
    cx_double value
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Clamp)(
    cx_int value,
    cx_int min,
    cx_int max
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Clamp, _2)(
    cx_long value,
    cx_long min,
    cx_long max
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Clamp, _3)(
    cx_float value,
    cx_float min,
    cx_float max
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Clamp, _4)(
    cx_double value,
    cx_double min,
    cx_double max
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Floor)(
    cx_int value
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Floor, _2)(
    cx_long value
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Floor, _3)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Floor, _4)(
    cx_double value
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Ceiling)(
    cx_int value
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Ceiling, _2)(
    cx_long value
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Ceiling, _3)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Ceiling, _4)(
    cx_double value
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Min)(
    cx_int value1,
    cx_int value2
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Min, _2)(
    cx_long value1,
    cx_long value2
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Min, _3)(
    cx_float value1,
    cx_float value2
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Min, _4)(
    cx_double value1,
    cx_double value2
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Math, Max)(
    cx_int value1,
    cx_int value2
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Math, Max, _2)(
    cx_long value1,
    cx_long value2
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Max, _3)(
    cx_float value1,
    cx_float value2
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Max, _4)(
    cx_double value1,
    cx_double value2
);
extern CX_EXPORT cx_float CX_ID_4(cxcore, System, Math, Round)(
    cx_float value
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Round, _2)(
    cx_float value,
    cx_int decimals
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Round, _3)(
    cx_double value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Round, _4)(
    cx_double value,
    cx_int decimals
);
extern CX_EXPORT cx_float CX_ID_4(cxcore, System, Math, Log)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Log, _2)(
    cx_double value
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Math, Log, _3)(
    cx_float value,
    cx_float newBase
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, Log, _4)(
    cx_double value,
    cx_double newBase
);
extern CX_EXPORT cx_float CX_ID_4(cxcore, System, Math, ReciprocalEstimate)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, ReciprocalEstimate, _2)(
    cx_double value
);
extern CX_EXPORT cx_float CX_ID_4(cxcore, System, Math, ReciprocalSqrtEstimate)(
    cx_float value
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Math, ReciprocalSqrtEstimate, _2)(
    cx_double value
);
extern CX_EXPORT cx_ptr CX_ID_4(cxcore, System, Memory, Alloc)(
    cx_uint size
);
extern CX_EXPORT cx_ptr CX_ID_4(cxcore, System, Memory, Realloc)(
    cx_ptr block,
    cx_uint size
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Memory, Free)(
    cx_ptr block
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Memory, Copy)(
    cx_ptr dest,
    cx_ptr src,
    cx_uint size
);
extern CX_EXPORT void CX_ID_4(cxcore, System, Random, __constructor)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_uint seed
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, Random) CX_ID_4(cxcore, System, Random, Create)();
extern CX_EXPORT cx_byte CX_ID_4(cxcore, System, Random, NextByte)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_byte CX_ID_5(cxcore, System, Random, NextByte, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_byte min,
    cx_byte max
);
extern CX_EXPORT cx_char CX_ID_4(cxcore, System, Random, NextChar)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_char min,
    cx_char max
);
extern CX_EXPORT cx_short CX_ID_4(cxcore, System, Random, NextShort)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_short CX_ID_5(cxcore, System, Random, NextShort, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_short min,
    cx_short max
);
extern CX_EXPORT cx_int CX_ID_4(cxcore, System, Random, NextInt)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_int CX_ID_5(cxcore, System, Random, NextInt, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_int min,
    cx_int max
);
extern CX_EXPORT cx_long CX_ID_4(cxcore, System, Random, NextLong)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_long CX_ID_5(cxcore, System, Random, NextLong, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_long min,
    cx_long max
);
extern CX_EXPORT cx_float CX_ID_4(cxcore, System, Random, NextFloat)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_float CX_ID_5(cxcore, System, Random, NextFloat, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_float min,
    cx_float max
);
extern CX_EXPORT cx_double CX_ID_4(cxcore, System, Random, NextDouble)(
    struct CX_ID_3(cxcore, System, Random)* __this    
);
extern CX_EXPORT cx_double CX_ID_5(cxcore, System, Random, NextDouble, _2)(
    struct CX_ID_3(cxcore, System, Random)* __this,
    cx_double min,
    cx_double max
);
extern CX_EXPORT const cx_sbyte CX_ID_5(cxcore, System, SByte, MinValue, __const_get)();
extern CX_EXPORT const cx_sbyte CX_ID_5(cxcore, System, SByte, MaxValue, __const_get)();
extern CX_EXPORT const cx_short CX_ID_5(cxcore, System, Short, MinValue, __const_get)();
extern CX_EXPORT const cx_short CX_ID_5(cxcore, System, Short, MaxValue, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, String)* CX_ID_5(cxcore, System, String, Empty, __const_get)();
extern CX_EXPORT cx_uint CX_ID_5(cxcore, System, String, Length, __const_get)(
    const struct CX_ID_3(cxcore, System, String)* __this    
);
extern CX_EXPORT cx_char CX_ID_5(cxcore, System, String, Item, __const_get)(
    const struct CX_ID_3(cxcore, System, String)* __this,
    cx_uint index    
);
extern void CX_ID_4(cxcore, System, String, __constructor)(
    struct CX_ID_3(cxcore, System, String)* __this    
);
extern void CX_ID_5(cxcore, System, String, __constructor, _2)(
    struct CX_ID_3(cxcore, System, String)* __this,
    cx_uint length,
    cx_ptr data
);
extern CX_EXPORT void CX_ID_5(cxcore, System, String, __constructor, _3)(
    struct CX_ID_3(cxcore, System, String)* __this,
    cx_uint length,
    cx_char ch
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, SystemDateTimeProvider, GetUtcNow)(
    struct CX_ID_3(cxcore, System, SystemDateTimeProvider)* __this    
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, DateTime) CX_ID_4(cxcore, System, SystemDateTimeProvider, GetLocalNow)(
    struct CX_ID_3(cxcore, System, SystemDateTimeProvider)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Ticks, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Days, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Hours, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Minutes, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Seconds, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_int CX_ID_5(cxcore, System, TimeSpan, Milliseconds, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalYears, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalMonths, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalWeeks, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalHours, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalMinutes, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalSeconds, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT const cx_long CX_ID_5(cxcore, System, TimeSpan, TotalMilliseconds, __const_get)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this    
);
extern CX_EXPORT void CX_ID_4(cxcore, System, TimeSpan, __constructor)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_ulong ticks
);
extern CX_EXPORT void CX_ID_5(cxcore, System, TimeSpan, __constructor, _2)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int days,
    cx_int hours,
    cx_int minutes,
    cx_int seconds,
    cx_int milliseconds
);
extern CX_EXPORT void CX_ID_5(cxcore, System, TimeSpan, __constructor, _3)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    struct CX_ID_3(cxcore, System, DateTime) from,
    struct CX_ID_3(cxcore, System, DateTime) to
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddDays)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int days
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddHours)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int hours
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddMinutes)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int minutes
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddSeconds)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int seconds
);
extern CX_EXPORT struct CX_ID_3(cxcore, System, TimeSpan) CX_ID_4(cxcore, System, TimeSpan, AddMilliseconds)(
    struct CX_ID_3(cxcore, System, TimeSpan)* __this,
    cx_int milliseconds
);
extern CX_EXPORT const cx_uint CX_ID_5(cxcore, System, UInt, MinValue, __const_get)();
extern CX_EXPORT const cx_uint CX_ID_5(cxcore, System, UInt, MaxValue, __const_get)();
extern CX_EXPORT const cx_ulong CX_ID_5(cxcore, System, ULong, MinValue, __const_get)();
extern CX_EXPORT const cx_ulong CX_ID_5(cxcore, System, ULong, MaxValue, __const_get)();
extern CX_EXPORT const cx_ushort CX_ID_5(cxcore, System, UShort, MinValue, __const_get)();
extern CX_EXPORT const cx_ushort CX_ID_5(cxcore, System, UShort, MaxValue, __const_get)();
extern CX_EXPORT const struct CX_ID_3(cxcore, System, Uuid) CX_ID_5(cxcore, System, Uuid, Zero, __const_get)();
extern CX_EXPORT void CX_ID_4(cxcore, System, Uuid, __constructor)(
    struct CX_ID_3(cxcore, System, Uuid)* __this,
    cx_uint a,
    cx_uint b,
    cx_uint c,
    cx_uint d
);
extern CX_EXPORT const struct CX_ID_3(cxcore, System, Void) CX_ID_5(cxcore, System, Void, Unit, __const_get)();


#endif // _CXCORE_H_
